<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run(): void
    {
        DB::table('products')->insert([
            [
                'name' => 'Tắt Đèn',
                'author' => 'Ngô Tất Tố',
                'description' => 'Một trong những tác phẩm tiêu biểu của văn học hiện thực phê phán Việt Nam.',
                'category' => 'Tiểu thuyết',
                'content' => 'Cuốn sách kể về cuộc sống khổ cực của chị Dậu, một người phụ nữ nông dân bị dồn vào đường cùng dưới ách thống trị của thực dân phong kiến. Chị Dậu phải đối mặt với những khó khăn chồng chất khi chồng bị bắt và con cái đói khát.',
                'publish_at' => 1939,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723467899/cvddd2o3nroemgefnfyv.jpg',
                'amount' => 50,
                'price' => 2.39,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Chí Phèo',
                'author' => 'Nam Cao',
                'description' => 'Một tác phẩm kinh điển về bi kịch cuộc đời của người nông dân Việt Nam thời phong kiến.',
                'category' => 'Truyện ngắn',
                'content' => 'Truyện kể về cuộc đời của Chí Phèo, một người nông dân bị xã hội phong kiến đẩy vào con đường tội lỗi. Bị tha hóa, Chí Phèo sống trong cơn say suốt ngày, cuối cùng bị giết chết khi nhận ra mình không còn đường quay lại làm người lương thiện.',
                'publish_at' => 1941,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723467991/mdjs3ykb5dy8qbhll4ac.webp',
                'amount' => 40,
                'price' => 2,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Số Đỏ',
                'author' => 'Vũ Trọng Phụng',
                'description' => 'Một tác phẩm châm biếm sâu sắc về xã hội Việt Nam thời Pháp thuộc.',
                'category' => 'Tiểu thuyết',
                'content' => 'Truyện kể về cuộc sống của Xuân Tóc Đỏ, một người vô công rồi nghề nhưng nhờ may mắn đã leo lên vị trí cao trong xã hội. Tác phẩm phê phán sự suy đồi của xã hội Việt Nam dưới sự ảnh hưởng của văn hóa Tây phương.',
                'publish_at' => 1936,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723468086/kwlvv94rilpknfgsyyhg.jpg',
                'amount' => 60,
                'price' => 3,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Đất Rừng Phương Nam',
                'author' => 'Đoàn Giỏi',
                'description' => 'Tác phẩm miêu tả thiên nhiên và cuộc sống vùng Nam Bộ.',
                'category' => 'Tiểu thuyết',
                'content' => 'Câu chuyện về cuộc sống phiêu lưu của cậu bé An giữa vùng rừng rậm Nam Bộ. Qua hành trình của An, tác phẩm ca ngợi vẻ đẹp của thiên nhiên và tinh thần quật cường của con người vùng đất Nam Bộ.',
                'publish_at' => 1957,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723468175/nefxc9k0t6qohlokntwk.jpg',
                'amount' => 55,
                'price' => 3,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nỗi Buồn Chiến Tranh',
                'author' => 'Bảo Ninh',
                'description' => 'Một tác phẩm gây chấn động về cuộc chiến tranh Việt Nam.',
                'category' => 'Tiểu thuyết',
                'content' => 'Truyện kể về cuộc đời của Kiên, một người lính trở về sau chiến tranh. Qua những ký ức đau thương của Kiên, tác phẩm phơi bày những mất mát và nỗi đau của cuộc chiến, đồng thời cũng là một lời tự vấn về sự hy sinh và ý nghĩa của cuộc sống.',
                'publish_at' => 1987,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723468255/u2bdcg35ddvo7opkkx64.jpg',
                'amount' => 70,
                'price' => 3.5,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Giông Tố',
                'author' => 'Vũ Trọng Phụng',
                'description' => 'Một tác phẩm phê phán xã hội phong kiến Việt Nam đầy kịch tính.',
                'category' => 'Tiểu thuyết',
                'content' => 'Câu chuyện về sự tha hóa và suy đồi đạo đức của xã hội phong kiến, qua cuộc đời của ông Đại, một người địa chủ tham lam, tàn ác. Tác phẩm là một lời cảnh tỉnh về sự tha hóa của con người khi bị quyền lực và tiền bạc làm mờ mắt.',
                'publish_at' => 1936,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723468378/p0jy5qsgu423eyuv60rr.jpg',
                'amount' => 50,
                'price' => 3,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Rừng Xà Nu',
                'author' => 'Nguyễn Trung Thành',
                'description' => 'Một tác phẩm viết về cuộc chiến tranh giải phóng miền Nam Việt Nam.',
                'category' => 'Truyện ngắn',
                'content' => 'Truyện kể về cuộc đấu tranh của người dân làng Xô Man, một làng dân tộc thiểu số ở Tây Nguyên, dưới sự lãnh đạo của cụ Mết và Tnú. Tác phẩm ca ngợi tinh thần đấu tranh anh dũng của người dân Tây Nguyên trong cuộc chiến chống Mỹ.',
                'publish_at' => 1965,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723468464/fmyzsap806my3blb64ue.jpg',
                'amount' => 60,
                'price' => 3,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Vợ Nhặt',
                'author' => 'Kim Lân',
                'description' => 'Một tác phẩm sâu sắc về tình người trong hoàn cảnh đói khát.',
                'category' => 'Truyện ngắn',
                'content' => 'Truyện kể về Tràng, một người nông dân nghèo khổ, đã "nhặt" được một người vợ trong hoàn cảnh nạn đói năm 1945. Cuộc sống khó khăn nhưng họ vẫn sống với nhau trong tình yêu thương và niềm hy vọng vào tương lai.',
                'publish_at' => 1962,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723468545/tdbeyipqfxcotehk3arm.jpg',
                'amount' => 40,
                'price' => 3,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Chí Phèo',
                'author' => 'Nam Cao',
                'description' => 'Một tác phẩm kinh điển về bi kịch cuộc đời của người nông dân Việt Nam thời phong kiến.',
                'category' => 'Truyện ngắn',
                'content' => 'Truyện kể về cuộc đời của Chí Phèo, một người nông dân bị xã hội phong kiến đẩy vào con đường tội lỗi. Bị tha hóa, Chí Phèo sống trong cơn say suốt ngày, cuối cùng bị giết chết khi nhận ra mình không còn đường quay lại làm người lương thiện.',
                'publish_at' => 1941,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723468615/garaqwtn6dmmahrqthey.webp',
                'amount' => 45,
                'price' => 3,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Người Mẹ Cầm Súng',
                'author' => 'Nguyễn Thi',
                'description' => 'Một tác phẩm ca ngợi tinh thần yêu nước và lòng dũng cảm của người phụ nữ Việt Nam trong chiến tranh.',
                'category' => 'Tiểu thuyết',
                'content' => 'Truyện kể về chị Út Tịch, một nữ du kích gan dạ và kiên cường, sẵn sàng hy sinh vì Tổ quốc. Tác phẩm tôn vinh những người mẹ Việt Nam anh hùng trong cuộc kháng chiến chống Mỹ.',
                'publish_at' => 1965,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723468685/rdqte7xlawqx8dt45dlw.webp',
                'amount' => 55,
                'price' => 3,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Cho Tôi Xin Một Vé Đi Tuổi Thơ',
                'author' => 'Nguyễn Nhật Ánh',
                'description' => 'Một tác phẩm nổi tiếng về tuổi thơ, khám phá những kỷ niệm và cảm xúc chân thật của trẻ em.',
                'category' => 'Văn học hiện đại, thiếu nhi',
                'content' => 'Câu chuyện xoay quanh những trải nghiệm và kỷ niệm tuổi thơ của nhóm bạn nhỏ. Họ cùng nhau trải qua các trò chơi, cuộc phiêu lưu, và các vấn đề trong cuộc sống.',
                'publish_at' => 2008,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723468816/dnarf2rw4fffjbqk0q01.jpg',
                'amount' => 50,
                'price' => 3,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Cánh Đồng Bất Tận',
                'author' => 'Nguyễn Ngọc Tư',
                'description' => 'Một tác phẩm văn học hiện đại nổi bật với những câu chuyện chân thực về cuộc sống và con người miền Tây Nam Bộ.',
                'category' => 'Văn học hiện đại',
                'content' => 'Cuốn sách gồm nhiều truyện ngắn miêu tả cuộc sống của người dân miền Tây qua những cái nhìn cảm xúc và tinh tế. Mỗi câu chuyện là một mảnh ghép của cuộc sống chân thật và đầy xúc động.',
                'publish_at' => 2005,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723469375/zbgkg44bgpc6c2kamhwu.jpg',
                'amount' => 60,
                'price' => 3.5,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hội Chợ Phù Hoa',
                'author' => 'Lê Minh Khuê',
                'description' => 'Một tập hợp các truyện ngắn của tác giả nổi tiếng với cách viết sâu sắc và tinh tế.',
                'category' => 'Văn học hiện đại',
                'content' => 'Sách chứa đựng những câu chuyện về cuộc sống hiện đại và các vấn đề xã hội, với cái nhìn sâu sắc về con người và mối quan hệ của họ.',
                'publish_at' => 2001,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723976538/wa3revs4g0prxbid0uza.webp',
                'amount' => 55,
                'price' => 3,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Người Đàn Ông Bán Bóng',
                'author' => 'Đỗ Hoàng Diệu',
                'description' => 'Một cuốn sách gây ấn tượng mạnh với câu chuyện đầy chất nhân văn và cảm xúc.',
                'category' => 'Văn học hiện đại',
                'content' => 'Câu chuyện xoay quanh nhân vật chính, một người đàn ông bán bóng tại một hội chợ, và những tình huống đặc biệt xảy ra trong cuộc sống của anh.',
                'publish_at' => 2010,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723469662/jbmnosuwb9x2wdozin5s.jpg',
                'amount' => 50,
                'price' => 3.5,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Truyện Ngắn Nam Cao',
                'author' => 'Nam Cao',
                'description' => 'Tập hợp các truyện ngắn nổi tiếng của Nam Cao, một trong những nhà văn vĩ đại của văn học Việt Nam.',
                'category' => 'Tiểu thuyết, truyện ngắn',
                'content' => 'Sách gồm các truyện ngắn phản ánh sâu sắc các vấn đề xã hội và số phận của con người trong xã hội phong kiến và đô thị.',
                'publish_at' => 2004,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723469750/wgwfkaw2caw0s4xfdknj.png',
                'amount' => 70,
                'price' => 3,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dưới Chân Cầu Mây',
                'author' => 'Phan Thị Vàng Anh',
                'description' => 'Một tác phẩm nổi bật với lối viết chân thực và cảm động về cuộc sống và tình yêu.',
                'category' => 'Văn học hiện đại',
                'content' => 'Câu chuyện diễn ra tại một khu vực miền núi, kể về những cuộc đời và tình cảm của những nhân vật sống dưới chân cầu mây.',
                'publish_at' => 2004,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723469819/rbgkpe2zm8omclwgilyw.jpg',
                'amount' => 50,
                'price' => 3,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Người Lớn Cô Đơn',
                'author' => 'Nguyễn Bảo Trung',
                'description' => 'Một cuốn sách về cuộc sống của người trưởng thành, phản ánh sự cô đơn và tìm kiếm ý nghĩa trong cuộc sống.',
                'category' => 'Văn học hiện đại',
                'content' => 'Câu chuyện về những người trưởng thành đối mặt với sự cô đơn và tìm kiếm sự kết nối và ý nghĩa trong cuộc sống hàng ngày.',
                'publish_at' => 2012,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723469915/kf9abyxhry6npqlvxqnl.jpg',
                'amount' => 45,
                'price' => 3.5,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Gào',
                'author' => 'Nguyễn Ngọc Thạch',
                'description' => 'Một tác phẩm văn học hiện đại nổi bật với cái nhìn sâu sắc và chân thành về cuộc sống và con người.',
                'category' => 'Văn học hiện đại',
                'content' => 'Câu chuyện xoay quanh nhân vật chính và những cuộc phiêu lưu, thử thách trong cuộc sống của anh.',
                'publish_at' => 2009,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723470194/uwuzggtpezx6tu0nxuqp.jpg',
                'amount' => 40,
                'price' => 4,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bóng Đè',
                'author' => 'Đỗ Hoàng Diệu',
                'description' => 'Một tác phẩm nổi bật với cốt truyện độc đáo và phong cách viết đầy cảm xúc.',
                'category' => 'Văn học hiện đại',
                'content' => 'Sách kể về những hiện tượng kỳ lạ và bí ẩn liên quan đến bóng đè, và cách mà nhân vật chính đối mặt với những thử thách trong cuộc sống.',
                'publish_at' => 2015,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723976475/zbxqcst4e2ewixveslje.jpg',
                'amount' => 45,
                'price' => 4,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sống Mòn',
                'author' => 'Nam Cao',
                'description' => 'Một tác phẩm nổi tiếng của Nam Cao, phản ánh sâu sắc về số phận con người và xã hội.',
                'category' => 'Tiểu thuyết',
                'content' => 'Câu chuyện kể về cuộc đời và những khó khăn mà nhân vật chính phải đối mặt, cùng với sự tìm kiếm ý nghĩa trong cuộc sống.',
                'publish_at' => 1942,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723470294/ukoxdhtsiwiqadr2ys2r.jpg',
                'amount' => 50,
                'price' => 3,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dế Mèn Phiêu Lưu Ký',
                'author' => 'Tô Hoài',
                'description' => 'Một tác phẩm kinh điển dành cho thiếu nhi, kể về cuộc phiêu lưu của Dế Mèn.',
                'category' => 'Văn học thiếu nhi',
                'content' => 'Câu chuyện kể về Dế Mèn, một chú dế nhỏ bé nhưng dũng cảm, và những chuyến phiêu lưu đầy thú vị của nó, cùng với những bài học quý giá về cuộc sống.',
                'publish_at' => 1941,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723470357/hyvofxrldacv6jnbfahp.jpg',
                'amount' => 50,
                'price' => 2.5,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kính Vạn Hoa',
                'author' => 'Nguyễn Nhật Ánh',
                'description' => 'Một tác phẩm nổi tiếng dành cho thiếu nhi và thanh thiếu niên, chứa đựng nhiều câu chuyện thú vị và cảm động.',
                'category' => 'Văn học thiếu nhi, thanh thiếu niên',
                'content' => 'Câu chuyện xoay quanh nhân vật chính và những cuộc phiêu lưu trong thế giới của kính vạn hoa, nơi mọi thứ trở nên kỳ diệu và đầy màu sắc.',
                'publish_at' => 1996,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723470471/nix1dbohu4yyr40wkgb3.jpg',
                'amount' => 60,
                'price' => 3,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Cho Tôi Xin Một Vé Đi Tuổi Thơ',
                'author' => 'Nguyễn Nhật Ánh',
                'description' => 'Một tác phẩm nổi tiếng về tuổi thơ, khám phá những kỷ niệm và cảm xúc chân thật của trẻ em.',
                'category' => 'Văn học hiện đại, thiếu nhi',
                'content' => 'Câu chuyện xoay quanh những trải nghiệm và kỷ niệm tuổi thơ của nhóm bạn nhỏ. Họ cùng nhau trải qua các trò chơi, cuộc phiêu lưu, và các vấn đề trong cuộc sống.',
                'publish_at' => 2008,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723470555/opqe8fap9jnphacnmzt4.jpg',
                'amount' => 50,
                'price' => 3.5,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hạt Giống Tâm Hồn',
                'author' => 'Nhiều tác giả',
                'description' => 'Một tập hợp các câu chuyện truyền cảm hứng và động viên, phù hợp với nhiều đối tượng độc giả.',
                'category' => 'Sách kỹ năng sống, tự lực',
                'content' => 'Cuốn sách chứa đựng các câu chuyện, bài học và lời khuyên giúp người đọc tìm thấy động lực và cảm hứng trong cuộc sống.',
                'publish_at' => 2007,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723470646/auby3hztueuk5j2pxfen.jpg',
                'amount' => 45,
                'price' => 4,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Harry Potter',
                'author' => 'J.K. Rowling (dịch)',
                'description' => 'Một trong những series sách nổi tiếng nhất thế giới về cuộc phiêu lưu của một cậu bé phù thủy.',
                'category' => 'Văn học giả tưởng',
                'content' => 'Câu chuyện theo chân Harry Potter, một cậu bé được phát hiện là phù thủy và học tại trường Hogwarts, nơi cậu trải qua nhiều cuộc phiêu lưu kỳ diệu.',
                'publish_at' => 2000,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723470735/mkir0bdzeurqjgdmnqyj.jpg',
                'amount' => 30,
                'price' => 7.5,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Chuyện Kể Cho Bé',
                'author' => 'Nguyễn Huy Thiệp',
                'description' => 'Một tập hợp các câu chuyện ngắn dành cho trẻ em, với nhiều bài học và thông điệp ý nghĩa.',
                'category' => 'Văn học thiếu nhi',
                'content' => 'Cuốn sách bao gồm nhiều câu chuyện thú vị và giáo dục cho trẻ em, giúp các em học hỏi và vui chơi qua từng trang sách.',
                'publish_at' => 2009,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723470901/zuykv8qofsibfkaowroz.jpg',
                'amount' => 55,
                'price' => 3,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Thám Tử Conan',
                'author' => 'Gosho Aoyama (dịch)',
                'description' => 'Một manga nổi tiếng về cuộc phiêu lưu của thám tử Conan và những vụ án hóc búa.',
                'category' => 'Manga, trinh thám',
                'content' => 'Câu chuyện xoay quanh Shinichi Kudo, một thám tử trẻ tuổi bị biến thành trẻ con và phải giải quyết các vụ án trong hình dạng mới của mình với tên gọi Conan Edogawa.',
                'publish_at' => 2000,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723471006/neztazpziizovca9aqne.jpg',
                'amount' => 40,
                'price' => 2,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Con Gái Bà Triệu',
                'author' => 'Nhiều tác giả',
                'description' => 'Một cuốn sách lịch sử và văn hóa về bà Triệu, một nhân vật lịch sử quan trọng của Việt Nam.',
                'category' => 'Lịch sử, văn hóa',
                'content' => 'Cuốn sách kể về cuộc đời và sự nghiệp của bà Triệu, một trong những nữ anh hùng của Việt Nam, và những đóng góp của bà cho lịch sử đất nước.',
                'publish_at' => 2008,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723477724/bgwbxplzjz04dokmy7tr.jpg',
                'amount' => 40,
                'price' => 3.5,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Truyện Cổ Tích Việt Nam',
                'author' => 'Nhiều tác giả',
                'description' => 'Một tập hợp các câu chuyện cổ tích nổi tiếng của Việt Nam, truyền tải các giá trị văn hóa và giáo dục.',
                'category' => 'Văn học thiếu nhi',
                'content' => 'Cuốn sách gồm các câu chuyện cổ tích truyền thống của Việt Nam, như "Cây tre trăm đốt," "Sự tích Hồ Gươm," và nhiều câu chuyện khác.',
                'publish_at' => 2005,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723477822/dtetknfkjto5iwjzi7a4.jpg',
                'amount' => 60,
                'price' => 2.5,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Đắc Nhân Tâm',
                'author' => 'Dale Carnegie (dịch)',
                'description' => 'Một trong những cuốn sách nổi tiếng nhất về nghệ thuật giao tiếp và xây dựng mối quan hệ.',
                'category' => 'Kỹ năng sống, phát triển cá nhân',
                'content' => 'Cuốn sách cung cấp những nguyên tắc cơ bản để tạo ra mối quan hệ tốt đẹp với người khác, bao gồm cách lắng nghe, khen ngợi chân thành, và cách giải quyết xung đột.',
                'publish_at' => 1936,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723477906/jwqzgb4aqkeqjkvshboa.jpg',
                'amount' => 100,
                'price' => 4.5,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Quẳng Gánh Lo Đi Và Vui Sống',
                'author' => 'Dale Carnegie (dịch)',
                'description' => 'Một cuốn sách giúp người đọc học cách giảm bớt lo âu và sống hạnh phúc hơn.',
                'category' => 'Kỹ năng sống, phát triển cá nhân',
                'content' => 'Cuốn sách cung cấp các phương pháp và kỹ thuật để giảm bớt lo lắng và căng thẳng trong cuộc sống hàng ngày, giúp người đọc tìm thấy sự bình yên và hạnh phúc.',
                'publish_at' => 1948,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723477988/qetebzdpd08t2v5jjsuz.jpg',
                'amount' => 80,
                'price' => 4.5,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Người Giàu Có Nhất Thành Babylon',
                'author' => 'George S. Clason (dịch)',
                'description' => 'Một cuốn sách về tài chính cá nhân và cách quản lý tiền bạc hiệu quả.',
                'category' => 'Tài chính cá nhân',
                'content' => 'Cuốn sách sử dụng các câu chuyện cổ xưa để truyền đạt những bài học về tài chính cá nhân, tiết kiệm, đầu tư và làm giàu.',
                'publish_at' => 1926,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723478114/yy4m98dr15kqdoenqcgf.jpg',
                'amount' => 70,
                'price' => 3.5,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sức Mạnh Của Thói Quen',
                'author' => 'Charles Duhigg (dịch)',
                'description' => 'Một cuốn sách nghiên cứu về thói quen và cách chúng ảnh hưởng đến cuộc sống của chúng ta.',
                'category' => 'Phát triển cá nhân, tâm lý học',
                'content' => 'Cuốn sách giải thích cách thói quen hình thành, ảnh hưởng đến cuộc sống của chúng ta, và cách thay đổi thói quen để đạt được kết quả tốt hơn.',
                'publish_at' => 2012,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723478214/pmbide14lk6zpbrree5f.jpg',
                'amount' => 90,
                'price' => 4,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bí Quyết Thành Công Của Người Do Thái',
                'author' => 'Nhiều tác giả',
                'description' => 'Một cuốn sách cung cấp cái nhìn về thành công và sự giàu có của cộng đồng người Do Thái.',
                'category' => 'Phát triển cá nhân, kinh doanh',
                'content' => 'Cuốn sách khám phá các nguyên tắc và chiến lược giúp cộng đồng người Do Thái đạt được thành công và thịnh vượng trong nhiều lĩnh vực.',
                'publish_at' => 2010,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723478304/groeb7pnfyspuxhjcnhm.jpg',
                'amount' => 60,
                'price' => 4,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nghệ Thuật Giao Tiếp',
                'author' => 'Larry King (dịch)',
                'description' => 'Một cuốn sách về kỹ năng giao tiếp từ một nhà báo nổi tiếng.',
                'category' => 'Kỹ năng sống, giao tiếp',
                'content' => 'Cuốn sách chia sẻ những bí quyết và kỹ năng giao tiếp mà Larry King đã học được trong suốt sự nghiệp phỏng vấn của mình, giúp người đọc nâng cao khả năng giao tiếp hiệu quả.',
                'publish_at' => 1999,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723478453/vcjgzhdw0qu0olbdnfuo.jpg',
                'amount' => 70,
                'price' => 3.5,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dạy Con Làm Giàu',
                'author' => 'Robert Kiyosaki (dịch)',
                'description' => 'Một cuốn sách nổi tiếng về tài chính cá nhân và cách dạy con cái về tiền bạc.',
                'category' => 'Tài chính cá nhân',
                'content' => 'Cuốn sách cung cấp các nguyên tắc tài chính cơ bản và cách giúp trẻ em học hỏi về tiền bạc, đầu tư và quản lý tài chính từ sớm.',
                'publish_at' => 1997,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723549524/nv5ubpszd9hsn6wycmjn.jpg',
                'amount' => 80,
                'price' => 6,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '7 Thói Quen Của Bạn Trẻ Thành Đạt',
                'author' => 'Sean Covey (dịch)',
                'description' => 'Một cuốn sách về phát triển cá nhân dành cho thanh thiếu niên.',
                'category' => 'Phát triển cá nhân, thanh thiếu niên',
                'content' => 'Cuốn sách trình bày bảy thói quen quan trọng giúp thanh thiếu niên phát triển bản thân, đạt được mục tiêu và trở thành người thành công.',
                'publish_at' => 1998,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723549599/yr0io9nnmqz6osaa69ir.jpg',
                'amount' => 60,
                'price' => 4,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sức Mạnh Của Hiện Tại',
                'author' => 'Eckhart Tolle (dịch)',
                'description' => 'Một cuốn sách về cách sống trong hiện tại và tìm thấy bình yên nội tâm.',
                'category' => 'Tâm lý học, phát triển cá nhân',
                'content' => 'Cuốn sách khám phá sức mạnh của việc sống trong khoảnh khắc hiện tại và cách loại bỏ lo âu và căng thẳng qua sự chú ý và ý thức hiện tại.',
                'publish_at' => 1997,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723549669/gwga4nrc5h2jszjhpgsu.png',
                'amount' => 70,
                'price' => 4.5,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tư Duy Tích Cực Thay Đổi Cuộc Sống',
                'author' => 'Norman Vincent Peale (dịch)',
                'description' => 'Một cuốn sách nổi tiếng về sức mạnh của tư duy tích cực trong việc thay đổi cuộc sống.',
                'category' => 'Phát triển cá nhân, tư duy tích cực',
                'content' => 'Cuốn sách cung cấp các phương pháp và kỹ thuật để áp dụng tư duy tích cực vào cuộc sống hàng ngày, giúp người đọc vượt qua khó khăn và đạt được mục tiêu.',
                'publish_at' => 1952,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723558525/sz3k9hmitboynrcy8d2p.jpg',
                'amount' => 60,
                'price' => 4.5,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bí Quyết Tay Trắng Thành Triệu Phú',
                'author' => 'Nhiều tác giả',
                'description' => 'Một cuốn sách chia sẻ các bí quyết và kinh nghiệm từ những người đã thành công trong việc xây dựng sự nghiệp và trở thành triệu phú từ hai bàn tay trắng.',
                'category' => 'Phát triển cá nhân, kinh doanh',
                'content' => 'Cuốn sách cung cấp các nguyên tắc và câu chuyện thực tế từ những người đã thành công trong việc tạo dựng sự nghiệp và tích lũy tài sản lớn mà không cần vốn ban đầu.',
                'publish_at' => 2010,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723558657/pb7pyg5cahogkscewlpd.jpg',
                'amount' => 50,
                'price' => 4.5,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nhà Giả Kim',
                'author' => 'Paulo Coelho (dịch)',
                'description' => 'Một cuốn tiểu thuyết nổi tiếng kể về hành trình tìm kiếm kho báu của một chàng chăn cừu, đồng thời là hành trình tìm kiếm ý nghĩa cuộc sống.',
                'category' => 'Văn học nước ngoài, tiểu thuyết',
                'content' => 'Câu chuyện kể về Santiago, một chàng chăn cừu trẻ, với ước mơ tìm kiếm kho báu, nhưng cuối cùng lại nhận ra rằng kho báu thực sự nằm trong cuộc hành trình và sự hiểu biết bản thân.',
                'publish_at' => 1988,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723558760/lbltl9bjuno3qcgowqs9.jpg',
                'amount' => 70,
                'price' => 4,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tuổi Trẻ Đáng Giá Bao Nhiêu',
                'author' => 'Rosie Nguyễn',
                'description' => 'Một cuốn sách truyền cảm hứng cho giới trẻ về giá trị của tuổi trẻ và cách sống trọn vẹn.',
                'category' => 'Phát triển cá nhân, tự truyện',
                'content' => 'Cuốn sách chia sẻ những kinh nghiệm và bài học từ tác giả, khuyến khích các bạn trẻ dám nghĩ, dám làm và sống hết mình với tuổi trẻ.',
                'publish_at' => 2016,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723558873/rja5avsudkvjaa1qoncr.jpg',
                'amount' => 100,
                'price' => 4.5,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Từ Tốt Đến Vĩ Đại',
                'author' => 'Jim Collins (dịch)',
                'description' => 'Một cuốn sách nghiên cứu về các công ty hàng đầu thế giới và những yếu tố giúp họ trở nên vĩ đại.',
                'category' => 'Kinh doanh, phát triển cá nhân',
                'content' => 'Cuốn sách phân tích các yếu tố và chiến lược mà những công ty từ tốt đến vĩ đại đã áp dụng, đồng thời đưa ra các bài học quý giá cho những ai muốn phát triển sự nghiệp và tổ chức của mình.',
                'publish_at' => 2001,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723559470/yhrozrcejmcbqbpswhio.png',
                'amount' => 80,
                'price' => 6,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Khởi Nghiệp Tinh Gọn',
                'author' => 'Eric Ries (dịch)',
                'description' => 'Một cuốn sách về phương pháp khởi nghiệp hiệu quả và tiết kiệm, giúp các doanh nghiệp mới tránh lãng phí và nhanh chóng phát triển.',
                'category' => 'Kinh doanh, khởi nghiệp',
                'content' => 'Cuốn sách giới thiệu về phương pháp Lean Startup, giúp các doanh nghiệp khởi nghiệp có thể thử nghiệm ý tưởng một cách nhanh chóng, giảm thiểu rủi ro và tối ưu hóa quá trình phát triển sản phẩm.',
                'publish_at' => 2011,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723631091/vnbuctnzzog0hns3joux.jpg',
                'amount' => 90,
                'price' => 4.5,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Lãnh Đạo Tích Cực',
                'author' => 'John C. Maxwell (dịch)',
                'description' => 'Một cuốn sách về nghệ thuật lãnh đạo, giúp bạn trở thành một người lãnh đạo tích cực và hiệu quả.',
                'category' => 'Phát triển cá nhân, lãnh đạo',
                'content' => 'Cuốn sách tập trung vào các nguyên tắc và kỹ năng lãnh đạo tích cực, từ việc phát triển bản thân đến việc truyền cảm hứng và hướng dẫn đội ngũ để đạt được mục tiêu chung.',
                'publish_at' => 2013,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723631189/zgx9ynsxwcan3ddywxcf.jpg',
                'amount' => 70,
                'price' => 5.5,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Thói Quen Thành Công',
                'author' => 'Stephen R. Covey (dịch)',
                'description' => 'Một cuốn sách nổi tiếng giới thiệu về những thói quen cần có để đạt được thành công trong cuộc sống và sự nghiệp.',
                'category' => 'Phát triển cá nhân',
                'content' => 'Cuốn sách trình bày về 7 thói quen quan trọng mà bất kỳ ai cũng cần phải áp dụng để đạt được sự thành công bền vững trong cả công việc và cuộc sống.',
                'publish_at' => 1989,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723631265/wrkrlusuhwbhe9cgsmjj.jpg',
                'amount' => 100,
                'price' => 4.5,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nghĩ Giàu Làm Giàu',
                'author' => 'Napoleon Hill (dịch)',
                'description' => 'Một trong những cuốn sách kinh điển về tư duy làm giàu và phát triển cá nhân.',
                'category' => 'Phát triển cá nhân, tư duy tích cực',
                'content' => 'Cuốn sách giới thiệu các nguyên tắc và triết lý về tư duy thành công, được xây dựng trên cơ sở nghiên cứu về những người giàu có và thành công nhất thời đại.',
                'publish_at' => 1937,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723631357/ba09h7xuuaebi1bsj0ou.jpg',
                'amount' => 90,
                'price' => 4,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Lãnh Đạo Không Chức Danh',
                'author' => 'Robin Sharma (dịch)',
                'description' => 'Cuốn sách giúp bạn khám phá cách lãnh đạo hiệu quả mà không cần đến chức danh, vị trí cao cấp.',
                'category' => 'Phát triển cá nhân, lãnh đạo',
                'content' => 'Cuốn sách hướng dẫn cách trở thành người lãnh đạo thực thụ dù không có chức danh, thông qua việc phát triển các kỹ năng lãnh đạo tự nhiên và truyền cảm hứng cho người khác.',
                'publish_at' => 2010,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723631442/shw7sncvarhlcelhkgsj.jpg',
                'amount' => 60,
                'price' => 4.5,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dạy Con Làm Giàu',
                'author' => 'Robert Kiyosaki (dịch)',
                'description' => 'Một cuốn sách nổi tiếng về tài chính cá nhân và cách dạy con cái về tiền bạc.',
                'category' => 'Tài chính cá nhân',
                'content' => 'Cuốn sách cung cấp các nguyên tắc tài chính cơ bản và cách giúp trẻ em học hỏi về tiền bạc, đầu tư và quản lý tài chính từ sớm.',
                'publish_at' => 1997,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723631564/ovliujqq3konszz22xjm.webp',
                'amount' => 80,
                'price' => 6,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Đại Nam Quốc Sử Diễn Ca',
                'author' => 'Lê Ngô Cát',
                'description' => 'Một tác phẩm văn học nổi tiếng, ghi lại lịch sử Việt Nam qua thơ ca.',
                'category' => 'Lịch sử, văn học',
                'content' => 'Cuốn sách diễn ca lịch sử Việt Nam từ thời Hùng Vương đến thời Nguyễn, qua các bài thơ lục bát dễ nhớ, được coi là một trong những tác phẩm văn học lịch sử quan trọng của Việt Nam.',
                'publish_at' => 1870,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723631722/wxloakrj9ngoficwhadf.jpg',
                'amount' => 40,
                'price' => 4,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bạch Đằng Giang Phú',
                'author' => 'Trương Hán Siêu ',
                'description' => 'Một tác phẩm văn học cổ điển, tôn vinh chiến thắng Bạch Đằng năm 938 của Ngô Quyền.',
                'category' => 'Lịch sử, văn học',
                'content' => 'Cuốn sách này tái hiện lại trận đánh Bạch Đằng qua văn thơ, ghi lại sự kiện lịch sử trọng đại trong quá trình bảo vệ độc lập của dân tộc Việt Nam.',
                'publish_at' => 1300,
                'image' => 'bach_dang_giang_phu.jpg',
                'amount' => 30,
                'price' => 3.5,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hồi Ký Trần Văn Giàu',
                'author' => 'Trần Văn Giàu',
                'description' => 'Hồi ký của nhà cách mạng Trần Văn Giàu, ghi lại những kỷ niệm và sự kiện quan trọng trong cuộc đời ông.',
                'category' => 'Lịch sử, hồi ký',
                'content' => 'Cuốn hồi ký này chia sẻ những trải nghiệm cá nhân và cái nhìn sâu sắc về những biến cố lịch sử lớn trong thế kỷ 20 từ góc nhìn của một nhà cách mạng kiên trung.',
                'publish_at' => 1995,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723631873/yq6zatnruw09muvsekmr.jpg',
                'amount' => 50,
                'price' => 4.5,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Trần Quốc Toản',
                'author' => 'Đào Duy Anh',
                'description' => 'Cuốn sách về cuộc đời và sự nghiệp của Trần Quốc Toản, người anh hùng nhỏ tuổi của lịch sử Việt Nam.',
                'category' => 'Lịch sử, tiểu sử',
                'content' => 'Câu chuyện về Trần Quốc Toản, người đã trở thành biểu tượng của lòng yêu nước và sự quyết tâm trong việc bảo vệ đất nước, được viết một cách sinh động và truyền cảm.',
                'publish_at' => 1938,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723815236/car4nqnec2rrqe0aw7hp.webp',
                'amount' => 40,
                'price' => 4.5,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hồ Chí Minh: Một Cuộc Đời',
                'author' => 'William J. Duiker (dịch)',
                'description' => 'Một tác phẩm nghiên cứu toàn diện về cuộc đời và sự nghiệp của Hồ Chí Minh, từ thời niên thiếu đến khi trở thành lãnh tụ cách mạng.',
                'category' => 'Lịch sử, tiểu sử',
                'content' => 'Cuốn sách này cung cấp cái nhìn sâu sắc và chi tiết về cuộc đời của Hồ Chí Minh, bao gồm những nỗ lực và thách thức mà ông đã vượt qua trong suốt quá trình đấu tranh giành độc lập cho Việt Nam.',
                'publish_at' => 2000,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723815372/hfaoow8iasgwaepbln6z.jpg',
                'amount' => 80,
                'price' => 6,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sử Ký Tư Mã Thiên',
                'author' => 'Tư Mã Thiên (dịch)',
                'description' => 'Một trong những tác phẩm lịch sử kinh điển của Trung Quốc, ghi lại lịch sử từ thời hoàng đế Hoàng Đế đến thời nhà Hán.',
                'category' => 'Lịch sử, văn học cổ điển',
                'content' => 'Cuốn sách này là một tác phẩm quan trọng trong lịch sử và văn học Trung Quốc, chứa đựng những câu chuyện, sự kiện lịch sử và nhân vật nổi bật trong suốt nhiều thế kỷ.',
                'publish_at' => 91,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723815625/nnfitugivh3jbcxzvpsd.jpg',
                'amount' => 60,
                'price' => 5.5,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Lược Sử Thời Gian',
                'author' => 'Stephen Hawking (dịch)',
                'description' => 'Cuốn sách nổi tiếng của Stephen Hawking về lịch sử của vũ trụ, từ Big Bang đến hố đen.',
                'category' => 'Khoa học, vũ trụ học',
                'content' => 'Cuốn sách này giải thích những khái niệm phức tạp về vũ trụ học bằng ngôn ngữ dễ hiểu, mang đến cho độc giả cái nhìn tổng quát về nguồn gốc và tương lai của vũ trụ.',
                'publish_at' => 1988,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723973672/k2r6lqca1odsycqgite9.jpg',
                'amount' => 80,
                'price' => 7.5,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Vũ Trụ',
                'author' => 'Carl Sagan (dịch)',
                'description' => 'Một tác phẩm kinh điển của Carl Sagan, khám phá những bí ẩn của vũ trụ và sự sống trên Trái Đất.',
                'category' => 'Khoa học, vũ trụ học',
                'content' => 'Cuốn sách này là một hành trình thú vị qua không gian và thời gian, khám phá nguồn gốc của các hành tinh, ngôi sao, và các hệ thống thiên văn trong vũ trụ.',
                'publish_at' => 1980,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723973745/p0tnjcvqndvugkn0pkts.jpg',
                'amount' => 90,
                'price' => 8.5,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Từ Điển Bách Khoa Tri Thức',
                'author' => 'Nhiều tác giả',
                'description' => 'Cuốn từ điển bách khoa toàn thư, cung cấp kiến thức rộng lớn về nhiều lĩnh vực khác nhau.',
                'category' => 'Khoa học, bách khoa toàn thư',
                'content' => 'Cuốn sách này là một tài liệu tham khảo quan trọng, chứa đựng thông tin chi tiết về mọi lĩnh vực từ khoa học tự nhiên, lịch sử, văn hóa đến nghệ thuật.',
                'publish_at' => 2005,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723973943/wp9hsmfylee4nnsjmjgd.jpg',
                'amount' => 100,
                'price' => 10,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sapiens: Lược Sử Loài Người',
                'author' => 'Yuval Noah Harari (dịch)',
                'description' => 'Cuốn sách nổi tiếng về sự phát triển và tiến hóa của loài người, từ quá khứ đến hiện tại.',
                'category' => 'Khoa học, lịch sử',
                'content' => 'Cuốn sách này khám phá những bước tiến vượt bậc của loài người, từ thời kỳ đồ đá đến cách mạng công nghiệp, và những tác động của chúng đến xã hội và văn hóa loài người hiện đại.',
                'publish_at' => 2011,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723974837/rah8yqbxmlqxbbkd9ud6.webp',
                'amount' => 90,
                'price' => 9,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nguồn Gốc Của Các Loài',
                'author' => 'Charles Darwin (dịch)',
                'description' => 'Cuốn sách kinh điển của Charles Darwin về thuyết tiến hóa và nguồn gốc của các loài.',
                'category' => 'Khoa học, sinh học',
                'content' => 'Cuốn sách này là nền tảng cho lý thuyết tiến hóa hiện đại, giải thích về sự chọn lọc tự nhiên và cách mà các loài động vật và thực vật đã tiến hóa qua hàng triệu năm.',
                'publish_at' => 1859,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723974748/x5bqsw9vjgfnzzv0zurj.jpg',
                'amount' => 100,
                'price' => 10,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tâm Lý Học Thành Công',
                'author' => 'Carol S. Dweck (dịch)',
                'description' => 'Cuốn sách của Carol S. Dweck về tư duy phát triển và cách nó ảnh hưởng đến thành công của con người.',
                'category' => 'Tâm lý học, phát triển cá nhân',
                'content' => 'Cuốn sách này giải thích sự khác biệt giữa tư duy cố định và tư duy phát triển, và cách thay đổi tư duy có thể dẫn đến thành công và phát triển bản thân.',
                'publish_at' => 2006,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723976247/abznck7x4kevvtwpzmxo.webp',
                'amount' => 80,
                'price' => 7.5,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Đàn Ông Sao Hỏa Đàn Bà Sao Kim',
                'author' => 'John Gray (dịch)',
                'description' => 'Cuốn sách nổi tiếng của John Gray về sự khác biệt tâm lý giữa nam và nữ và cách giao tiếp hiệu quả.',
                'category' => 'Tâm lý học, mối quan hệ',
                'content' => 'Cuốn sách này giúp người đọc hiểu và chấp nhận sự khác biệt trong cách suy nghĩ và hành xử giữa nam và nữ, từ đó xây dựng các mối quan hệ tốt đẹp hơn.',
                'publish_at' => 1992,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723974983/uip1sou0kkcbguxtbsg5.jpg',
                'amount' => 90,
                'price' => 8,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tâm Lý Học Hành Vi',
                'author' => 'B.F. Skinner (dịch)',
                'description' => 'Cuốn sách của B.F. Skinner về lý thuyết hành vi và những ứng dụng của nó trong tâm lý học.',
                'category' => 'Tâm lý học, hành vi',
                'content' => 'Cuốn sách này khám phá cách hành vi con người được hình thành và thay đổi qua các điều kiện học tập và phản ứng, và ảnh hưởng của môi trường đến hành vi của con người.',
                'publish_at' => 1953,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723975027/mxw2d4fmsfuxemdsafkh.jpg',
                'amount' => 70,
                'price' => 7,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sức Mạnh Của Sự Tĩnh Lặng',
                'author' => 'Ryan Holiday (dịch)',
                'description' => 'Cuốn sách của Ryan Holiday về sức mạnh của sự tĩnh lặng và tư duy sâu sắc.',
                'category' => 'Tâm lý học, phát triển cá nhân',
                'content' => 'Cuốn sách này đề cập đến cách tìm kiếm sự tĩnh lặng nội tâm, giải phóng khỏi sự ồn ào của cuộc sống hiện đại và đạt được sự tự do và sáng tạo.',
                'publish_at' => 2019,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723975077/kvr294gpnkghb9zrmm41.jpg',
                'amount' => 85,
                'price' => 8.5,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tâm Lý Học Trẻ Em',
                'author' => 'Jean Piaget (dịch)',
                'description' => 'Cuốn sách của Jean Piaget về sự phát triển tâm lý của trẻ em.',
                'category' => 'Tâm lý học, trẻ em',
                'content' => 'Cuốn sách này khám phá các giai đoạn phát triển tâm lý của trẻ em, từ suy nghĩ, nhận thức đến hành vi, và cách cha mẹ và giáo viên có thể hỗ trợ quá trình này.',
                'publish_at' => 1936,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723975123/tharmf9l08ceupdjqggf.jpg',
                'amount' => 75,
                'price' => 7.5,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tâm Lý Học Nhân Cách',
                'author' => 'Carl Rogers (dịch)',
                'description' => 'Cuốn sách của Carl Rogers về lý thuyết nhân cách và những ứng dụng của nó trong tâm lý học.',
                'category' => 'Tâm lý học, nhân cách',
                'content' => 'Cuốn sách này giải thích về cách nhân cách con người được hình thành, phát triển và ảnh hưởng đến hành vi và cảm xúc của họ, cùng với các phương pháp tiếp cận tâm lý học nhân văn.',
                'publish_at' => 1951,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723975163/fzxczo8yshxdzpo6uavh.webp',
                'amount' => 80,
                'price' => 8,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Những Đòn Tâm Lý Trong Thuyết Phục',
                'author' => 'Robert B. Cialdini (dịch)',
                'description' => 'Cuốn sách của Robert B. Cialdini về những chiến lược tâm lý hiệu quả trong việc thuyết phục người khác.',
                'category' => 'Tâm lý học, thuyết phục',
                'content' => 'Cuốn sách này giải thích các nguyên tắc tâm lý đứng sau sự thuyết phục và cách áp dụng chúng trong các tình huống thực tế, từ bán hàng đến giao tiếp hàng ngày.',
                'publish_at' => 1984,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723975212/rpehb7s1cpxohwjq1lto.jpg',
                'amount' => 95,
                'price' => 9,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tâm Lý Học Xã Hội',
                'author' => 'Elliot Aronson (dịch)',
                'description' => 'Cuốn sách của Elliot Aronson về tâm lý học xã hội và ảnh hưởng của xã hội đến hành vi con người.',
                'category' => 'Tâm lý học, xã hội',
                'content' => 'Cuốn sách này khám phá cách mà các cá nhân bị ảnh hưởng bởi môi trường xã hội, các nhóm, và các yếu tố văn hóa, và cách xã hội định hình hành vi và thái độ của con người.',
                'publish_at' => 1972,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723975257/ileqy0773aj2ihzm8chi.jpg',
                'amount' => 85,
                'price' => 8.5,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Những Nguyên Tắc Vàng Trong Tâm Lý Học',
                'author' => 'Martin Seligman (dịch)',
                'description' => 'Cuốn sách của Martin Seligman về các nguyên tắc tâm lý học tích cực và cách áp dụng chúng để đạt được hạnh phúc và thành công.',
                'category' => 'Tâm lý học, phát triển cá nhân',
                'content' => 'Cuốn sách này trình bày các nguyên tắc cơ bản của tâm lý học tích cực, bao gồm cách xây dựng tư duy tích cực, phát triển các kỹ năng sống, và đạt được trạng thái hạnh phúc bền vững.',
                'publish_at' => 2011,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723975463/dk2slwnrs3d7if50tt1w.jpg',
                'amount' => 90,
                'price' => 9,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hành Trình Đông Nam Á',
                'author' => 'Nhiều tác giả',
                'description' => 'Cuốn sách về những chuyến đi và trải nghiệm phong phú tại các quốc gia Đông Nam Á.',
                'category' => 'Du lịch, khám phá',
                'content' => 'Cuốn sách này ghi lại những hành trình xuyên qua các quốc gia Đông Nam Á, từ cảnh quan thiên nhiên hùng vĩ đến những nét văn hóa đặc sắc, phong tục tập quán địa phương.',
                'publish_at' => 2018,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723975643/xcqzlorsmfrgmwhfgipd.jpg',
                'amount' => 70,
                'price' => 6,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name' => 'Ẩm Thực 3 Miền',
                'author' => 'Nhiều tác giả',
                'description' => 'Cuốn sách về ẩm thực của ba miền Bắc, Trung, Nam Việt Nam.',
                'category' => 'Ẩm thực, nấu ăn',
                'content' => 'Cuốn sách này giới thiệu những món ăn đặc trưng của ba miền Bắc, Trung, Nam Việt Nam, từ các món ăn dân dã đến các món đặc sản, cùng với những câu chuyện về nguồn gốc và ý nghĩa của từng món ăn.',
                'publish_at' => 2016,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723976059/s0ftf1ovmuutpdp46j6r.webp',
                'amount' => 125,
                'price' => 5.5,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'To Kill a Mockingbird',
                'author' => 'Harper Lee',
                'description' => 'Một tác phẩm kinh điển của văn học Mỹ, phản ánh các vấn đề xã hội và chủng tộc.',
                'category' => 'Tiểu thuyết, Văn học',
                'content' => 'Cuốn sách kể câu chuyện về sự trưởng thành và lòng dũng cảm của một cô bé trong bối cảnh phân biệt chủng tộc ở miền Nam nước Mỹ.',
                'publish_at' => 1960,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723990868/ljtezxq9tnnfvn7qbadn.webp',
                'amount' => 50,
                'price' => 10.0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '1984',
                'author' => 'George Orwell',
                'description' => 'Một tác phẩm dystopian nổi tiếng, miêu tả một xã hội dưới sự kiểm soát của chế độ toàn trị.',
                'category' => 'Khoa học viễn tưởng, Chính trị',
                'content' => 'Cuốn sách xoay quanh cuộc sống của Winston Smith trong một thế giới mà mọi hành động và tư tưởng đều bị giám sát chặt chẽ.',
                'publish_at' => 1949,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723990905/paxklnkfv7cpvpfixqek.jpg',
                'amount' => 45,
                'price' => 12.0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Pride and Prejudice',
                'author' => 'Jane Austen',
                'description' => 'Một tác phẩm lãng mạn cổ điển, khám phá các chủ đề của tình yêu, gia đình và xã hội.',
                'category' => 'Tiểu thuyết, Văn học',
                'content' => 'Cuốn sách kể câu chuyện về Elizabeth Bennet và hành trình tìm kiếm tình yêu đích thực trong xã hội Anh thế kỷ 19.',
                'publish_at' => 1813,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723990946/hwauuwux198xxa51yagw.webp',
                'amount' => 60,
                'price' => 8.0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'The Catcher in the Rye',
                'author' => 'J.D. Salinger',
                'description' => 'Một tác phẩm văn học hiện đại nổi tiếng về sự trưởng thành và những khủng hoảng của tuổi dậy thì.',
                'category' => 'Tiểu thuyết, Văn học',
                'content' => 'Cuốn sách theo chân Holden Caulfield trong hành trình tìm kiếm ý nghĩa và mục đích cuộc sống ở New York.',
                'publish_at' => 1951,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723990980/ql0b09s55rhv8opibbry.jpg',
                'amount' => 40,
                'price' => 11.0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'The Great Gatsby',
                'author' => 'F. Scott Fitzgerald',
                'description' => 'Một tác phẩm văn học cổ điển miêu tả xã hội Mỹ trong thời kỳ Hoàng kim và những ảo tưởng của cái gọi là giấc mơ Mỹ.',
                'category' => 'Tiểu thuyết, Văn học',
                'content' => 'Cuốn sách kể về cuộc sống và những ảo tưởng của Jay Gatsby, một người đàn ông giàu có nhưng không thể tìm được hạnh phúc.',
                'publish_at' => 1925,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723991028/yksqqzb3i3wabnmf6big.webp',
                'amount' => 55,
                'price' => 9.0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Brave New World',
                'author' => 'Aldous Huxley',
                'description' => 'Một tác phẩm khoa học viễn tưởng khám phá một xã hội tương lai trong đó con người được kiểm soát hoàn toàn.',
                'category' => 'Khoa học viễn tưởng, Xã hội',
                'content' => 'Cuốn sách miêu tả một thế giới nơi con người sống trong sự hài hòa giả tạo nhưng thiếu đi sự tự do và cảm xúc thật sự.',
                'publish_at' => 1932,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723991069/ks2fwyo4evzodhvfd6to.jpg',
                'amount' => 35,
                'price' => 13.0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'The Hobbit',
                'author' => 'J.R.R. Tolkien',
                'description' => 'Một tác phẩm kỳ ảo nổi tiếng kể về cuộc phiêu lưu của Bilbo Baggins.',
                'category' => 'Kỳ ảo, Tiểu thuyết',
                'content' => 'Cuốn sách theo chân Bilbo Baggins, một hobbit bình thường, trong cuộc hành trình để lấy lại kho báu từ rồng Smaug.',
                'publish_at' => 1937,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723991104/x3dj3wvonyntidzoefog.jpg',
                'amount' => 50,
                'price' => 14.0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Les Misérables',
                'author' => 'Victor Hugo',
                'description' => 'Một tác phẩm vĩ đại về xã hội Pháp thế kỷ 19, với các chủ đề về tình yêu, công lý và sự tha thứ.',
                'category' => 'Tiểu thuyết, Văn học',
                'content' => 'Cuốn sách theo dõi cuộc đời của Jean Valjean và các nhân vật khác trong bối cảnh của những bất công xã hội ở Pháp.',
                'publish_at' => 1862,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723991155/oywd42pmqcfpvsdxoxm4.webp',
                'amount' => 40,
                'price' => 12.0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Moby-Dick',
                'author' => 'Herman Melville',
                'description' => 'Một tác phẩm cổ điển của văn học Mỹ, tập trung vào cuộc săn lùng cá voi khổng lồ Moby Dick.',
                'category' => 'Tiểu thuyết, Văn học',
                'content' => 'Cuốn sách kể về hành trình của thuyền trưởng Ahab và cuộc săn lùng không ngừng nghỉ để bắt được con cá voi trắng Moby Dick.',
                'publish_at' => 1851,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723991189/zjrlpuaaxmerbk9djkes.jpg',
                'amount' => 30,
                'price' => 10.0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'The Odyssey',
                'author' => 'Homer',
                'description' => 'Một trong những tác phẩm vĩ đại của văn học cổ đại, kể về cuộc hành trình trở về quê hương của Odysseus.',
                'category' => 'Huyền thoại, Văn học',
                'content' => 'Cuốn sách miêu tả những cuộc phiêu lưu và thử thách mà Odysseus gặp phải trong hành trình trở về Ithaca sau cuộc chiến thành Troy.',
                'publish_at' => 800 ,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723991222/jj9vvgurquavmkqudhk1.jpg',
                'amount' => 25,
                'price' => 15.0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'One Hundred Years of Solitude',
                'author' => 'Gabriel García Márquez',
                'description' => 'Một kiệt tác của văn học Latin America, miêu tả sự lên xuống của gia tộc Buendía qua nhiều thế hệ.',
                'category' => 'Tiểu thuyết, Văn học',
                'content' => 'Cuốn sách kể về lịch sử của gia tộc Buendía ở thị trấn Macondo và sự hòa quyện giữa hiện thực và hư cấu trong cuộc sống của họ.',
                'publish_at' => 1967,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723991259/k6um4tcywqxnc8ljs8cp.jpg',
                'amount' => 40,
                'price' => 11.0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'War and Peace',
                'author' => 'Leo Tolstoy',
                'description' => 'Một trong những tác phẩm vĩ đại của văn học Nga, phản ánh tình hình xã hội và chiến tranh trong thế kỷ 19.',
                'category' => 'Tiểu thuyết, Lịch sử',
                'content' => 'Cuốn sách mô tả cuộc sống của nhiều nhân vật trong bối cảnh chiến tranh Napoléon và sự thay đổi của xã hội Nga.',
                'publish_at' => 1869,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723991399/y7x7zidmliu6b5h9g81b.jpg',
                'amount' => 35,
                'price' => 15.0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'The Catcher in the Rye',
                'author' => 'J.D. Salinger',
                'description' => 'Một tác phẩm nổi tiếng về sự trưởng thành và những khủng hoảng của tuổi dậy thì.',
                'category' => 'Tiểu thuyết, Văn học',
                'content' => 'Cuốn sách theo chân Holden Caulfield trong hành trình tìm kiếm ý nghĩa cuộc sống ở New York.',
                'publish_at' => 1951,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723991439/sqlbmerzjcujq6vihy38.webp',
                'amount' => 40,
                'price' => 11.0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Catch-22',
                'author' => 'Joseph Heller',
                'description' => 'Một tác phẩm satirical về cuộc chiến tranh thế giới thứ hai và những nghịch lý của quân đội.',
                'category' => 'Tiểu thuyết, Chiến tranh',
                'content' => 'Cuốn sách theo chân Yossarian, một phi công quân đội Mỹ trong Thế chiến II, và những khôi hài trong cuộc sống quân đội của anh.',
                'publish_at' => 1961,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723991466/e5om2sfsxnrrm7plejhj.jpg',
                'amount' => 30,
                'price' => 12.0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'The Picture of Dorian Gray',
                'author' => 'Oscar Wilde',
                'description' => 'Một tác phẩm văn học về sự suy đồi đạo đức và cái giá của cái đẹp vĩnh cửu.',
                'category' => 'Tiểu thuyết, Văn học',
                'content' => 'Cuốn sách kể về Dorian Gray, người có bức chân dung phản ánh sự suy đồi của anh, trong khi chính anh không thay đổi.',
                'publish_at' => 1890,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723991502/rkevcup6fu8uhc1t57ds.jpg',
                'amount' => 25,
                'price' => 10.0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Don Quixote',
                'author' => 'Miguel de Cervantes',
                'description' => 'Một tác phẩm cổ điển của văn học Tây Ban Nha, kể về cuộc phiêu lưu của Don Quixote và người phụ tá của ông, Sancho Panza.',
                'category' => 'Tiểu thuyết, Văn học',
                'content' => 'Cuốn sách miêu tả những cuộc phiêu lưu hài hước và bi kịch của Don Quixote khi ông tìm kiếm những cuộc phiêu lưu để chứng minh lý tưởng của mình.',
                'publish_at' => 1605,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723991534/mut6y2xkrfgyh4wfhsfz.webp',
                'amount' => 20,
                'price' => 14.0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Fahrenheit 451',
                'author' => 'Ray Bradbury',
                'description' => 'Một tác phẩm khoa học viễn tưởng miêu tả một thế giới nơi sách bị cấm và bị thiêu hủy.',
                'category' => 'Khoa học viễn tưởng, Xã hội',
                'content' => 'Cuốn sách theo chân Guy Montag, một lính cứu hỏa trong tương lai nơi sách bị cấm, và hành trình của anh để tìm kiếm sự tự do trí tuệ.',
                'publish_at' => 1953,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723991562/df5e0qfzz6prphl7ig3m.jpg',
                'amount' => 30,
                'price' => 11.0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Anna Karenina',
                'author' => 'Leo Tolstoy',
                'description' => 'Một tác phẩm vĩ đại về tình yêu, gia đình và xã hội Nga thế kỷ 19.',
                'category' => 'Tiểu thuyết, Văn học',
                'content' => 'Cuốn sách theo dõi cuộc đời của Anna Karenina và những hệ lụy từ tình yêu của cô với một người đàn ông khác ngoài chồng mình.',
                'publish_at' => 1877,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723991587/o98p9e6t16icn33b3oqp.jpg',
                'amount' => 35,
                'price' => 14.0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'The Brothers Karamazov',
                'author' => 'Fyodor Dostoevsky',
                'description' => 'Một tác phẩm vĩ đại của văn học Nga về các vấn đề tôn giáo, đạo đức và gia đình.',
                'category' => 'Tiểu thuyết, Tôn giáo',
                'content' => 'Cuốn sách kể về cuộc sống của gia đình Karamazov và những xung đột tâm lý và đạo đức mà họ phải đối mặt.',
                'publish_at' => 1880,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723991652/xproajjwoqpcgs9mgl9j.jpg',
                'amount' => 30,
                'price' => 12.0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dune',
                'author' => 'Frank Herbert',
                'description' => 'Một tác phẩm khoa học viễn tưởng nổi tiếng về cuộc chiến tranh và chính trị trên hành tinh cát Arrakis.',
                'category' => 'Khoa học viễn tưởng, Chính trị',
                'content' => 'Cuốn sách theo chân Paul Atreides và cuộc chiến tranh giành quyền kiểm soát hành tinh Arrakis, nơi sản xuất chất gia vị quan trọng.',
                'publish_at' => 1965,
                'image' => 'https://res.cloudinary.com/dficfkyug/image/upload/v1723991687/vqxk3sqfisb1wfc6karu.jpg',
                'amount' => 40,
                'price' => 13.0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'The Alchemist',
                'author' => 'Paulo Coelho',
                'description' => 'Một câu chuyện về sự tìm kiếm ý nghĩa cuộc sống và tự thực hiện giấc mơ cá nhân.',
                'category' => 'Tiểu thuyết, Tự truyện',
                'content' => 'Cuốn sách kể về Santiago, một người chăn cừu trẻ tuổi, trong hành trình tìm kiếm kho báu và khám phá ý nghĩa cuộc sống.',
                'publish_at' => 1988,
                'image' => 'The Stranger',
                'amount' => 45,
                'price' => 9.0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ]);
    }
}
